server:
  port: 8089


jwt:
  secret: cDQgcWIx2cd6Dnj1Za0FmPNFOB5dmW1A
  internalSecret: 9GSHO1glgDuEOAQrMps44LitSeaVNmMI40bl7Sxra30zZ2nXylPrzsbfgTVftLXE


spring:
  application:
    name: api-gateway

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KC_CLIENT_ID}
            client-secret: ${KC_SECRET}
            authorization-grant-type: authorization_code
            scope: openid, profile, roles, email
        provider:
          keycloak:
            issuer-uri: ${KC_ISSUE_URL}
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUE_URL}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.security: DEBUG
