server:
  port: 8084

jwt:
  internalSecret: 9GSHO1glgDuEOAQrMps44LitSeaVNmMI40bl7Sxra30zZ2nXylPrzsbfgTVftLXE

app:
  kafka:
    topic:
      reserve-inventory-command: ${KAFKA_RESERVED_INVENTORY_COMMAND_TOPIC}
      payment-completed: ${KAFKA_PAYMENT_COMPLETED_TOPIC}
      payment-failed: ${KAFKA_PAYMENT_FAILED_TOPIC}
      inventory-reserved: ${KAFKA_INVENTORY_RESERVED_TOPIC}
      inventory-rejected: ${KAFKA_INVENTORY_REJECTED_TOPIC}
      inventory-released: ${KAFKA_INVENTORY_RELEASED_TOPIC}
      create-payment-command: ${KAFKA_CREATE_PAYMENT_COMMAND_TOPIC}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${ORDER_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUE_URL}


  kafka:
    bootstrap-servers: ${KAFKA_HOST}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka