server:
  port: 8082

jwt:
  internalSecret: 9GSHO1glgDuEOAQrMps44LitSeaVNmMI40bl7Sxra30zZ2nXylPrzsbfgTVftLXE

app:
  kafka:
    topic:
      create-inventory-command: ${KAFKA_CREATE_INVENTORY_COMMAND_TOPIC}

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KC_CLIENT_ID}
            client-secret: ${KC_SECRET}
            authorization-grant-type: authorization_code
            scope: openid, profile, roles, email
        provider:
          keycloak:
            issuer-uri: ${KC_ISSUE_URL}
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUE_URL}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${PRODUCT_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: update
#    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: product-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.springframework.security: DEBUG


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka