server:
  port: 8083

jwt:
  internalSecret: 9GSHO1glgDuEOAQrMps44LitSeaVNmMI40bl7Sxra30zZ2nXylPrzsbfgTVftLXE

app:
  kafka:
    topic:
      create-inventory-command: ${KAFKA_CREATE_INVENTORY_COMMAND_TOPIC}
      inventory-reserved: ${KAFKA_INVENTORY_RESERVED_TOPIC}
      inventory-released: ${KAFKA_INVENTORY_RELEASED_TOPIC}
      reserve-inventory-command: ${KAFKA_RESERVED_INVENTORY_COMMAND_TOPIC}
      inventory-rejected: ${KAFKA_INVENTORY_REJECTED_TOPIC}


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUE_URL}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${INVENTORY_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka