KC_CLIENT_ID: demo-microservices
KC_ISSUE_URL: http://localhost:8080/realms/microservices-realm
KC_SECRET: GI5owoexfHr2cSHAiwrqgS930PkXOFuH
KAFKA_HOST: localhost:9092
POSTGRES_HOST: localhost:5435
INVENTORY_DB: inventory_db
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
KAFKA_PRODUCT_CREATED_TOPIC: product.created
KAFKA_INVENTORY_RESERVED_TOPIC: inventory.reserved
KAFKA_INVENTORY_RELEASED_TOPIC: inventory.released
KAFKA_ORDER_CREATED_TOPIC: order.created
KAFKA_INVENTORY_REJECTED_TOPIC: inventory.rejected
KAFKA_PAYMENT_FAILED_TOPIC: payment.failed